### ISSUE TITLE
Enabled Analytics tracking

### ISSUE THREAD

**Issue by mmlngl** [100Shapes/100Shapes.com-Lithium#12]
We've currently got the placeholder in until we launch.

**Comment by mmlngl** [comment]
• Check the tracking ID
• Enable the analytics

**Comment by paolomemoli** [comment]
we need to pull out the slugs of posts and attach them to CTA, Newsletter signup and Callouts directives

**Comment by paolomemoli** [comment]
See commit: 3ad84dfbab077769

for references to analytics tracking which need changing

**Comment by mmlngl** [comment]
Done in build.
