### ISSUE TITLE
Make a sitemap

### ISSUE THREAD

**Issue by mmlngl** [100Shapes/100Shapes.com-Lithium#8]
Link to it, small, in the footer.

Include landing pages.

**Comment by mmlngl** [comment]
We could generate it on the backend, and use Angular to just proxy the request. Might save the pain.

**Comment by mmlngl** [comment]
Done.

[Doing exactly this with the backend](https://github.com/100Shapes/100Shapes.com-content-API/commit/180c1f8bd36d3363033b4817ca113019d6b3de66).

Next we need to tell nginx to route a certain url (i.e. `/sitemap.xml`) to the backend.

**Comment by mmlngl** [comment]
@memolipd you happy with [the hardcoded URL](https://github.com/100Shapes/100Shapes.com-Lithium/commit/3c8a0cc12f5ef21c9c6bcd06cac68654085cd02c#diff-daaf2fceca49ed034eace91c4e875653R59)?

**Comment by mmlngl** [comment]
I'm also not sure of the order in the `nginx.conf`. Want to move these `location` checks before the `prerender` stuff?

**Comment by mmlngl** [comment]
@memolipd can you clear around anything you don't need from frontend's `nginx.conf`

**Comment by paolomemoli** [comment]
turns out you can only do subdomain redirection through our DNS provider, therefore we'll need to the code put in the frontend nginx config.

**Comment by mmlngl** [comment]
This is done.
